language: cpp
sudo: false

branches:
  except:
    - gh-pages

addons:
  apt_packages:
      - libgmp3-dev
      - parallel
      - valgrind

install:
 - git clone --depth=2 https://github.com/gap-system/gap.git gap
  - pwd
  - ( cd gap && ./configure --with-gmp=system && make && make bootstrap-pkg-minimal)
  - ( cd gap/pkg && wget http://www.gap-system.org/pub/gap/gap4/tar.bz2/packages/atlasrep1r5p0.tar.bz2 && tar -xf atlasrep1r5p0.tar.bz2 )
  - ( cd gap/pkg && git clone --depth=2 https://github.com/gap-packages/io && cd io && ./autogen.sh && ./configure && make )
  - ( cd gap/pkg && git clone --depth=2 https://github.com/gap-system/gap-packages/ferret && cd ferret && ./autogen.sh && ./configure && make )
  - pwd
  - ln -s $(pwd) gap/pkg/images

script:
  - gap/bin/gap.sh -l "$(pwd)/gap-root/;" -A tst/testall.g

